[package]
name = "my-blogs-with-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.5.0-alpha.2", features = ["fullstack"] }
# dioxus-liveview = { version = "0.5.0-alpha.2" }
# tokio = { version = "1.36.0", features = ["full"] }

[features]
default = []
server = ["dioxus/axum"]
web = ["dioxus/web"]
